server:
  port: 8081

spring:
  application:
    name: dtt-spring-boot-2.x-javadoc

  profiles:
    #derby|h2|hsql|mariadb|mysql|oracle|db2|postgresql|sqlserver
    active: h2

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
