logging:
  level:
    #cn.alphahub.dtt.plus.framework.core.template.DefaultTemplateResolver: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    jdbc.sqltiming: debug

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.31.23:1521/lwj
    username: C##DTT
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.example.domain.dtt,com.example.domain.order
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


alphahub:
  dtt:
    show-sql: on
    all-in-one-table:
      enable: true
      filename: AllInOne.sql
      filepath: /Users/weasley/Downloads
    code-generator:
      is-enable: off
      include-controller: on
      include-interface: on
      override-exists: off
      remove-prefix: ''
      base-classes:
        - com.example.domain.dtt.DttMember
      module-name: dtt
      module-package: com.example
      module-path: /Users/weasley/Development/IdeaProjects/dtt-spring-boot-parent/dtt-spring-boot-tests/dtt-spring-boot-2.x-javadoc
    data-type-mapper:
      oracle:
        enable-column-upper-case: on
