logging:
  level:
    #cn.alphahub.dtt.plus.framework.core.DefaultTemplateResolver: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    jdbc.sqltiming: debug

spring:
  datasource:
    embedded-database-connection: hsqldb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:/Users/weasley/Development/IdeaProjects/mydtt-plus-spring-boot-parent/embedded-db/hsqldb;create=true;shutdown=true
    username:
    password:

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.example.domain.dtt,com.example.domain.order
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alphahub:
  dtt:
    show-sql: on
    all-in-one-table:
      enable: true
      filename: AllInOne.sql
      filepath: /Users/weasley/Downloads
    code-generator:
      is-enable: on
      base-classes:
        - com.example.domain.dtt.DttMember
      module-name: dtt
      module-package: com.example
      module-path: /Users/weasley/Development/IdeaProjects/mydtt-plus-spring-boot-parent/mydtt-plus-spring-boot-starter-tests/mydtt-plus-spring-boot-2-x
