CREATE TABLE `order_refund`
(
    `address`                       varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收货地址合并省市区',
    `id`                            int NOT NULL AUTO_INCREMENT,
    `channel`                       int                                                           DEFAULT NULL COMMENT '1 线下E端 2 线上C端 3 线下B端',
    `return_deduction_score_amount` decimal(10, 0)                                                DEFAULT NULL COMMENT '退单归还抵扣金额（优医币，邦指数）',
    `return_deduction_card_amount`  decimal(10, 0)                                                DEFAULT NULL COMMENT '退单归还抵扣金额（礼品卡）',
    `sku_id`                        varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT 'sku id',
    `pay_no`                        varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '支付交易单号',
    `status`                        int                                                           DEFAULT NULL COMMENT '1 待退款 2 退款关闭 3 商家审核 4 商品寄回 5 商家确认退款 6 退款成功 7 退货待审核',
    `goods_name`                    varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '商品名称',
    `supplier_name`                 varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '供应商名称',
    `supplier_full_name`            varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '供应商全称',
    `order_no`                      varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '订单号',
    `order_id`                      int                                                           DEFAULT NULL COMMENT '订单id',
    `buyer_id`                      int                                                           DEFAULT NULL COMMENT '买家用户ID',
    `invoice_no`                    varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '快递单号',
    `goods_num`                     int                                                           DEFAULT NULL COMMENT '商品数量',
    `goods_id`                      int                                                           DEFAULT NULL COMMENT 'goods id',
    `item_id`                       int                                                           DEFAULT NULL COMMENT 'item id',
    `refund_no`                     varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '退单号',
    `finished_time`                 datetime                                                      DEFAULT NULL COMMENT '退单完成时间',
    `refund_amount`                 decimal(10, 0)                                                DEFAULT NULL COMMENT '退款金额',
    `buyer_name`                    varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '购买者用户名',
    `buyer_tel`                     varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '购买者电话',
    `cancel_reason`                 varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '退单原因',
    `pay_way_code`                  varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收付代码（支付类型代码）',
    `pay_way_name`                  varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收付名称（支付类型名称）',
    `refund_type`                   int                                                           DEFAULT NULL COMMENT '1 退款 2 退货 3 退货退款',
    `refund_carriage_amount`        decimal(10, 0)                                                DEFAULT NULL COMMENT '运费退款金额',
    `refund_pay_dis_amount`         decimal(10, 0)                                                DEFAULT NULL COMMENT '非现金支付退款金额',
    `chain_shop_id`                 int                                                           DEFAULT NULL COMMENT '连锁店id',
    `chain_shop_name`               varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '连锁店名称',
    `retail_shop_id`                int                                                           DEFAULT NULL COMMENT '门店id',
    `retail_shop_name`              varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '门店名称',
    `third_transaction_no`          varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '三方流水号',
    `supplement_reason`             varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '补充原因',
    `rejective_reason`              varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '拒绝原因',
    `out_member_id`                 varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '大会员系统的会员id',
    `return_deduction_amount`       decimal(10, 0)                                                DEFAULT NULL COMMENT '退单归还抵扣金额',
    `return_health_coin`            int                                                           DEFAULT NULL COMMENT '退单归还抵扣优医币',
    `return_bang_coin`              int                                                           DEFAULT NULL COMMENT '退单归还抵扣邦指数',
    `express_method`                int                                                           DEFAULT NULL COMMENT '退货物流方式 1.无退货物流 2.原运单退回 3.新运单退回',
    `picture_url`                   varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '退款图片凭证',
    `update_time`                   datetime                                                      DEFAULT NULL COMMENT '更新时间',
    `supplier_id`                   int                                                           DEFAULT NULL COMMENT '供应商id',
    `platform_id`                   int                                                           DEFAULT NULL COMMENT '平台：0 无 1 普通会员 2 医生-优医邦 3 药店（邦甸园）',
    `create_time`                   datetime                                                      DEFAULT NULL COMMENT '创建时间',
    `express_code`                  varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '物流公司code',
    `del_flag`                      int                                                           DEFAULT NULL COMMENT '是否删除  1 是  0  否',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_general_ci COMMENT ='<p>\n 退单主表\n </p>';
