logging:
  level:
    #cn.alphahub.dtt.plus.framework.core.template.DefaultTemplateResolver: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    jdbc.sqltiming: debug

spring:
  datasource:
    #-- create a file system database
    #jdbc:derby:sampleDB;create=true

    #-- create a file system database using the databaseName attribute
    #jdbc:derby:;databaseName=newDB;create=true

    #-- create an in-memory database using the embedded driver
    #jdbc:derby:memory:myInMemDB;create=true

    #-- create an in-memory database using the databaseName attribute
    #jdbc:derby:;databaseName=memory:myInMemDB;create=true

    #-- create an in-memory database using the Network Server
    #jdbc:derby://localhost:1527/memory:myInMemDB;create=tru
    embedded-database-connection: derby
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    #url: jdbc:derby:;databaseName=memory:dtt_demo;create=true
    url: jdbc:derby:/Users/weasley/Development/IdeaProjects/dtt-spring-boot-parent/embedded-db/derby;create=true
    username: app
    password: ""

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.example.domain.dtt,com.example.domain.order
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alphahub:
  dtt:
    show-sql: on
    all-in-one-table:
      enable: true
      filename: AllInOne.sql
      filepath: /Users/weasley/Downloads
    code-generator:
      is-enable: on
      module-name: dtt
      module-package: com.example
      module-path: /Users/weasley/Development/IdeaProjects/dtt-spring-boot-parent/dtt-spring-boot-tests/dtt-spring-boot-2-x
      base-classes:
        - com.example.domain.dtt.DttMember
        - com.example.domain.dtt.DttPerson
